on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.201
      - name: Install dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish -c Release
      - name: Upload publish results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results
          path: src/TgToVkPoster/bin/Release/net6.0/publish/